Repository ZenBit-Tech/faq_team_be, pull requests merged in 2024-06, with the labels that each got.

#5 Feature/auth via google
  .env.example
  .eslintrc.js
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/common/enums/route-name.enum.ts
  src/entities/enums/user-status.enum.ts
  src/entities/user.entity.ts
  src/main.ts
  src/migrations/1717436910582-addPasswordNullable.ts
  src/migrations/1717582467152-changeUserStatus.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/dto/request/sign-up.request.dto.ts
  src/modules/google-auth/dto/response/google-auth.response.dto.ts
  src/modules/google-auth/enums/google-auth-action.enum.ts
  src/modules/google-auth/google-auth.controller.ts
  src/modules/google-auth/google-auth.module.ts
  src/modules/google-auth/google-auth.service.ts
  src/modules/google-auth/google.strategy.ts
  src/modules/google-auth/interfaces/google.interfaces.ts
  src/modules/mail/mail.module.ts
Labels: documentation, enhancement

#7 Feature/sign in
  ormconfig.ts
  package-lock.json
  package.json
  src/common/configs/database/mysql.service.ts
  src/common/filters/httpException.filter.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/request/sign-in.request.dto.ts
  src/modules/auth/dto/response/sign-in.dto.ts
  src/modules/auth/local-auth.guard.ts
  src/modules/auth/local.strategy.ts
  src/modules/user/user.module.ts
  src/utils/constants.ts
  src/utils/constants/docsTexts.ts
  src/utils/constants/errorTexts.ts
  src/utils/generalConstants.ts
Labels: documentation, enhancement

#6 Feature/update user
  package-lock.json
  package.json
  src/common/enums/route-name.enum.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/mail/templates/email-verify.hbs
  src/modules/user/dto/update-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.service.ts
Labels: documentation, enhancement

#8 added admin service, otp functionality and cleaned up
  src/entities/enums/user-role.enum.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/sign-in.request.dto.ts
  src/modules/auth/dto/sign-in.response.dto.ts
  src/modules/auth/dto/sign-up.request.dto.ts
  src/modules/auth/local.strategy.ts
  src/modules/auth/services/auth.service.ts
  src/modules/auth/services/super-admin-seed.service.ts
  src/modules/auth/types/super-admin.type.ts
  src/utils/constants/docsTexts.ts
  src/utils/constants/errorTexts.ts
  src/utils/generalConstants.ts
Labels: enhancement

#9 Make some code refactoring and add otp service
  .env.example
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/common/enums/error-message.enum.ts
  src/common/enums/route-name.enum.ts
  src/common/enums/table-name.enum.ts
  src/common/enums/user-role.enum.ts
  src/common/enums/user-status.enum.ts
  src/entities/user.entity.ts
  src/main.ts
  src/migrations/1716909088898-createUserEntity.ts
  src/migrations/1717436910582-addPasswordNullable.ts
  src/migrations/1717582467152-changeUserStatus.ts
  src/migrations/1717934137516-createUserEntity.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/dto/send-otp.request.dto.ts
  src/modules/auth/dto/sign-in.response.dto.ts
  src/modules/auth/dto/user.response.dto.ts
  src/modules/auth/dto/verify-otp.request.dto.ts
  src/modules/auth/guards/jwtAuthGuard.ts
  src/modules/auth/guards/local-auth.guard.ts
  src/modules/auth/services/auth.service.ts
  src/modules/auth/services/otp.service.ts
  src/modules/auth/services/super-admin-seed.service.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/auth/strategies/local.strategy.ts
  src/modules/auth/types/jwt-validate.ts
  src/modules/google-auth/dto/google-auth.response.dto.ts
  src/modules/google-auth/google-auth.controller.ts
  src/modules/google-auth/google-auth.module.ts
  src/modules/google-auth/google-auth.service.ts
  src/modules/google-auth/interfaces/google.interfaces.ts
  src/modules/mail/mail.module.ts
  src/modules/mail/mail.service.ts
  src/modules/repository/repository.module.ts
  src/modules/repository/services/user.repository.ts
  src/modules/user/dto/update-user.dto.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/modules/user/user.service.ts
  src/utils/generalConstants.ts
Labels: documentation, enhancement

#10 Feature/rate and leave review
  src/common/enums/error-message.enum.ts
  src/common/enums/route-name.enum.ts
  src/common/enums/table-name.enum.ts
  src/entities/rate.entity.ts
  src/entities/review.entity.ts
  src/entities/user.entity.ts
  src/migrations/1717934137516-createUserEntity.ts
  src/migrations/1718130564918-createUserEntity.ts
  src/migrations/1718391282330-addRateAndReview.ts
  src/modules/auth/services/auth.service.ts
  src/modules/google-auth/google-auth.service.ts
  src/modules/repository/repository.module.ts
  src/modules/repository/services/rate.repository.ts
  src/modules/repository/services/review.repository.ts
  src/modules/repository/services/user.repository.ts
  src/modules/user/dto/delete-review.request.dto.ts
  src/modules/user/dto/make-review.request.dto.ts
  src/modules/user/dto/rate-request.dto.ts
  src/modules/user/services/rate.service.ts
  src/modules/user/services/review.service.ts
  src/modules/user/services/user.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/utils/generalConstants.ts
Labels: documentation, enhancement

#11 Created endpoints for fetching and deleting users as superadmin
  package-lock.json
  package.json
  src/common/enums/route-name.enum.ts
  src/common/enums/sort.enum.ts
  src/migrations/1718391282330-addRateAndReview.ts
  src/migrations/1718539905027-addRateAndReview.ts
  src/modules/user/dto/filter-users.dto.ts
  src/modules/user/services/user-seed.service.ts
  src/modules/user/services/user.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/utils/constants/fakeUsers.ts
Labels: enhancement

#12 Feature/fill profile
  .env.example
  .eslintrc.js
  package-lock.json
  package.json
  src/app.module.ts
  src/common/configs/database/mysql.module.ts
  src/common/configs/database/mysql.service.ts
  src/common/enums/aws-bucket-path.enum.ts
  src/common/enums/route-name.enum.ts
  src/common/enums/table-name.enum.ts
  src/entities/models/base.entity.ts
  src/entities/order.entity.ts
  src/entities/product.entity.ts
  src/entities/rate.entity.ts
  src/entities/review.entity.ts
  src/entities/user.entity.ts
  src/main.ts
  src/migrations/1716533019325-test-migration.ts
  src/migrations/1718130564918-createUserEntity.ts
  src/migrations/1718539905027-addRateAndReview.ts
  src/migrations/1718795972753-current.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/dto/sign-in.response.dto.ts
  src/modules/auth/dto/verify-otp.request.dto.ts
  src/modules/auth/services/auth.service.ts
  src/modules/auth/services/otp.service.ts
  src/modules/auth/services/super-admin-seed.service.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/auth/strategies/local.strategy.ts
  src/modules/google-auth/dto/google-auth.response.dto.ts
  src/modules/google-auth/google-auth.controller.ts
  src/modules/google-auth/google-auth.module.ts
  src/modules/google-auth/google-auth.service.ts
  src/modules/mail/mail.module.ts
  src/modules/mail/mail.service.ts
  src/modules/repository/repository.module.ts
  src/modules/repository/services/rate.repository.ts
  src/modules/repository/services/review.repository.ts
  src/modules/repository/services/user.repository.ts
  src/modules/user/dto/filter-users.dto.ts
  src/modules/user/dto/general-info.dto.ts
  src/modules/user/dto/update-user.dto.ts
  src/modules/user/services/rate.service.ts
  src/modules/user/services/review.service.ts
  src/modules/user/services/s3.service.ts
  src/modules/user/services/user-seed.service.ts
  src/modules/user/services/user.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
  src/utils/constants/fakeUsers.ts
Labels: enhancement

#15 fix: recreate migration
  package-lock.json
  package.json
  src/entities/user.entity.ts
  src/migrations/1718745166902-addRateAndReview.ts
  src/migrations/1718792445261-addFollowEntity.ts
  src/migrations/1718795972753-current.ts
  src/migrations/1718830293356-addAvgRateToUserEntity.ts
  src/migrations/1718887160103-baseMigration.ts
  src/modules/user/services/user.service.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.module.ts
Labels: bug

#18 Feature/add reates reviews seed
  src/common/configs/database/db-seed.service.ts
  src/common/configs/database/mysql.module.ts
  src/entities/product.entity.ts
  src/entities/review.entity.ts
  src/modules/user/user.module.ts
  src/utils/constants/fakeConstants.ts
  src/utils/constants/fakeRates.ts
  src/utils/constants/fakeReviews.ts
Labels: enhancement

#19 fix: added product name to latest orders
  src/modules/order/order.controller.ts
  src/modules/order/order.service.ts
  src/modules/repository/services/order.repository.ts
  src/utils/constants/fakeConstants.ts
  src/utils/constants/seedFunctions.ts
Labels: bug

#20 Fix/product repository
  src/modules/order/order.controller.ts
  src/modules/order/order.service.ts
  src/modules/product/dto/filter-products.request.dto.ts
  src/modules/repository/services/product.repository.ts
  src/modules/repository/services/user.repository.ts
  src/modules/user/dto/filter-users.request.dto.ts
Labels: bug
